# Generated by Django 4.2.8 on 2024-02-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_enrollment_duedate_enrollment_paymentstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='DueDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
