# Generated by Django 4.2.8 on 2024-02-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_attendance_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='attendance',
            name='Fullname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
