# Generated by Django 4.2.8 on 2024-02-24 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_remove_attendance_phonenumber_attendance_fullname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendance',
            new_name='WorkoutLog',
        ),
    ]
