# Generated by Django 4.2.8 on 2024-02-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_rename_attendance_workoutlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='r1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='r2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='r3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='w1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='w2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='w3',
            field=models.CharField(default='', max_length=200),
        ),
    ]
