# Generated by Django 4.2.8 on 2024-02-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_workoutlog_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='mail',
            field=models.EmailField(default='manjunathar609@gmail.com', max_length=254),
        ),
    ]
