# Generated by Django 4.2.8 on 2024-02-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_alter_workoutlog_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='mail',
            field=models.EmailField(default='kumudal19@gmail.com', max_length=254),
        ),
    ]
